[2025-04-12T05:17:30.969+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-12T05:17:30.977+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: triphobo_etl_pipeline.upload_raw_attractions manual__2025-04-12T05:00:15.126362+00:00 [queued]>
[2025-04-12T05:17:30.979+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: triphobo_etl_pipeline.upload_raw_attractions manual__2025-04-12T05:00:15.126362+00:00 [queued]>
[2025-04-12T05:17:30.980+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-12T05:17:30.984+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): upload_raw_attractions> on 2025-04-12 05:00:15.126362+00:00
[2025-04-12T05:17:30.988+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=640) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-12T05:17:30.990+0000] {standard_task_runner.py:72} INFO - Started process 641 to run task
[2025-04-12T05:17:30.991+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'triphobo_etl_pipeline', 'upload_raw_attractions', 'manual__2025-04-12T05:00:15.126362+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/trip_dag.py', '--cfg-path', '/tmp/tmpd6vg2gb_']
[2025-04-12T05:17:30.993+0000] {standard_task_runner.py:105} INFO - Job 116: Subtask upload_raw_attractions
[2025-04-12T05:17:31.023+0000] {task_command.py:467} INFO - Running <TaskInstance: triphobo_etl_pipeline.upload_raw_attractions manual__2025-04-12T05:00:15.126362+00:00 [running]> on host 1dd90d5609a8
[2025-04-12T05:17:31.056+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='triphobo_etl_pipeline' AIRFLOW_CTX_TASK_ID='upload_raw_attractions' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T05:00:15.126362+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-12T05:00:15.126362+00:00'
[2025-04-12T05:17:31.056+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-12T05:17:31.174+0000] {upload_to_S3.py:36} ERROR - Failed to upload /tmp/triphobo_data/multi_city_attractions.csv to s3://bigdatafinal2025/raw/multi_city_attractions.csv: [Errno 2] No such file or directory: '/tmp/triphobo_data/multi_city_attractions.csv'
[2025-04-12T05:17:31.174+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-12T05:17:31.179+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-12T05:17:31.179+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=triphobo_etl_pipeline, task_id=upload_raw_attractions, run_id=manual__2025-04-12T05:00:15.126362+00:00, execution_date=20250412T050015, start_date=20250412T051730, end_date=20250412T051731
[2025-04-12T05:17:31.215+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-12T05:17:31.231+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-12T05:17:31.232+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
