[2025-04-12T03:27:35.808+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-12T03:27:35.814+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: triphobo_etl_pipeline.upload_raw_tours manual__2025-04-11T23:43:23.931280+00:00 [queued]>
[2025-04-12T03:27:35.817+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: triphobo_etl_pipeline.upload_raw_tours manual__2025-04-11T23:43:23.931280+00:00 [queued]>
[2025-04-12T03:27:35.817+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-12T03:27:35.822+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): upload_raw_tours> on 2025-04-11 23:43:23.931280+00:00
[2025-04-12T03:27:35.826+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2500) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-12T03:27:35.827+0000] {standard_task_runner.py:72} INFO - Started process 2508 to run task
[2025-04-12T03:27:35.827+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'triphobo_etl_pipeline', 'upload_raw_tours', 'manual__2025-04-11T23:43:23.931280+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/trip_dag.py', '--cfg-path', '/tmp/tmp5yjai1rz']
[2025-04-12T03:27:35.831+0000] {standard_task_runner.py:105} INFO - Job 77: Subtask upload_raw_tours
[2025-04-12T03:27:35.856+0000] {task_command.py:467} INFO - Running <TaskInstance: triphobo_etl_pipeline.upload_raw_tours manual__2025-04-11T23:43:23.931280+00:00 [running]> on host ef93b6d60ab1
[2025-04-12T03:27:35.889+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='triphobo_etl_pipeline' AIRFLOW_CTX_TASK_ID='upload_raw_tours' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T23:43:23.931280+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-11T23:43:23.931280+00:00'
[2025-04-12T03:27:35.890+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-12T03:27:38.036+0000] {logging_mixin.py:190} INFO - ‚ùå Failed to upload /Users/srushtipatil/Desktop/Northeastern University/DAMG7245_Big Data/Project/multi_city_attractions.csv: [Errno 2] No such file or directory: '/Users/srushtipatil/Desktop/Northeastern University/DAMG7245_Big Data/Project/multi_city_attractions.csv'
[2025-04-12T03:27:38.036+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-12T03:27:38.041+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-12T03:27:38.041+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=triphobo_etl_pipeline, task_id=upload_raw_tours, run_id=manual__2025-04-11T23:43:23.931280+00:00, execution_date=20250411T234323, start_date=20250412T032735, end_date=20250412T032738
[2025-04-12T03:27:38.064+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-12T03:27:38.075+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-12T03:27:38.075+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
