[2025-04-13T23:03:24.874+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T23:03:24.881+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ihg_hotels_dag.load_to_snowflake manual__2025-04-13T23:02:20.489285+00:00 [queued]>
[2025-04-13T23:03:24.884+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ihg_hotels_dag.load_to_snowflake manual__2025-04-13T23:02:20.489285+00:00 [queued]>
[2025-04-13T23:03:24.884+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-04-13T23:03:24.888+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_snowflake> on 2025-04-13 23:02:20.489285+00:00
[2025-04-13T23:03:24.892+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1293) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T23:03:24.893+0000] {standard_task_runner.py:72} INFO - Started process 1294 to run task
[2025-04-13T23:03:24.893+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ihg_hotels_dag', 'load_to_snowflake', 'manual__2025-04-13T23:02:20.489285+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/hotel_scrape_dag.py', '--cfg-path', '/tmp/tmp5f210nta']
[2025-04-13T23:03:24.894+0000] {standard_task_runner.py:105} INFO - Job 238: Subtask load_to_snowflake
[2025-04-13T23:03:24.913+0000] {task_command.py:467} INFO - Running <TaskInstance: ihg_hotels_dag.load_to_snowflake manual__2025-04-13T23:02:20.489285+00:00 [running]> on host 599bf25ffed0
[2025-04-13T23:03:24.946+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ihg_hotels_dag' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T23:02:20.489285+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-13T23:02:20.489285+00:00'
[2025-04-13T23:03:24.947+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-13T23:03:24.953+0000] {hotel_scrape_dag.py:826} INFO - Connecting to Snowflake...
[2025-04-13T23:03:24.953+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-13T23:03:24.954+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-13T23:03:24.954+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-13T23:03:26.391+0000] {hotel_scrape_dag.py:847} INFO - Creating stage and table in Snowflake...
[2025-04-13T23:03:26.647+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-13T23:03:26.943+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-13T23:03:26.944+0000] {hotel_scrape_dag.py:873} INFO - Copying data from S3 to Snowflake table...
[2025-04-13T23:03:27.733+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-13T23:03:27.936+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-13T23:03:27.937+0000] {hotel_scrape_dag.py:884} INFO - âœ… Data loaded into Snowflake table: hotels (220 rows)
[2025-04-13T23:03:27.937+0000] {connection.py:789} INFO - closed
[2025-04-13T23:03:27.982+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-04-13T23:03:28.041+0000] {python.py:240} INFO - Done. Returned value was: 220
[2025-04-13T23:03:28.060+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-13T23:03:28.060+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ihg_hotels_dag, task_id=load_to_snowflake, run_id=manual__2025-04-13T23:02:20.489285+00:00, execution_date=20250413T230220, start_date=20250413T230324, end_date=20250413T230328
[2025-04-13T23:03:28.102+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-13T23:03:28.110+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T23:03:28.110+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
