[2025-04-17T21:20:14.526+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T21:20:14.531+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ihg_hotels_dag.geocode_hotels manual__2025-04-17T21:19:30.573976+00:00 [queued]>
[2025-04-17T21:20:14.534+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ihg_hotels_dag.geocode_hotels manual__2025-04-17T21:19:30.573976+00:00 [queued]>
[2025-04-17T21:20:14.534+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-17T21:20:14.538+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): geocode_hotels> on 2025-04-17 21:19:30.573976+00:00
[2025-04-17T21:20:14.541+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1289) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-17T21:20:14.542+0000] {standard_task_runner.py:72} INFO - Started process 1290 to run task
[2025-04-17T21:20:14.543+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ihg_hotels_dag', 'geocode_hotels', 'manual__2025-04-17T21:19:30.573976+00:00', '--job-id', '399', '--raw', '--subdir', 'DAGS_FOLDER/hotel_scrape_dag.py', '--cfg-path', '/tmp/tmpusnuesml']
[2025-04-17T21:20:14.544+0000] {standard_task_runner.py:105} INFO - Job 399: Subtask geocode_hotels
[2025-04-17T21:20:14.563+0000] {task_command.py:467} INFO - Running <TaskInstance: ihg_hotels_dag.geocode_hotels manual__2025-04-17T21:19:30.573976+00:00 [running]> on host 4d0efc92e922
[2025-04-17T21:20:14.594+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ihg_hotels_dag' AIRFLOW_CTX_TASK_ID='geocode_hotels' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T21:19:30.573976+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T21:19:30.573976+00:00'
[2025-04-17T21:20:14.595+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-17T21:20:14.601+0000] {hotel_scrape_dag.py:485} INFO - Starting geocoding process
[2025-04-17T21:20:14.602+0000] {hotel_scrape_dag.py:561} ERROR - Error in geocoding process: name 'csv' is not defined
Traceback (most recent call last):
  File "/opt/airflow/dags/hotel_scrape_dag.py", line 489, in add_geocoding_data
    reader = csv.DictReader(input_file)
             ^^^
NameError: name 'csv' is not defined. Did you forget to import 'csv'
[2025-04-17T21:20:14.603+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/hotel_scrape_dag.py", line 489, in add_geocoding_data
    reader = csv.DictReader(input_file)
             ^^^
NameError: name 'csv' is not defined. Did you forget to import 'csv'
[2025-04-17T21:20:14.606+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ihg_hotels_dag, task_id=geocode_hotels, run_id=manual__2025-04-17T21:19:30.573976+00:00, execution_date=20250417T211930, start_date=20250417T212014, end_date=20250417T212014
[2025-04-17T21:20:14.610+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-17T21:20:14.610+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 399 for task geocode_hotels (name 'csv' is not defined; 1290)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/hotel_scrape_dag.py", line 489, in add_geocoding_data
    reader = csv.DictReader(input_file)
             ^^^
NameError: name 'csv' is not defined. Did you forget to import 'csv'
[2025-04-17T21:20:14.641+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-17T21:20:14.649+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T21:20:14.651+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
