[2025-04-14T20:14:25.694+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T20:14:25.699+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ihg_hotels_dag.load_to_snowflake manual__2025-04-14T20:13:32.219908+00:00 [queued]>
[2025-04-14T20:14:25.702+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ihg_hotels_dag.load_to_snowflake manual__2025-04-14T20:13:32.219908+00:00 [queued]>
[2025-04-14T20:14:25.702+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-04-14T20:14:25.706+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_snowflake> on 2025-04-14 20:13:32.219908+00:00
[2025-04-14T20:14:25.709+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=106) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-14T20:14:25.709+0000] {standard_task_runner.py:72} INFO - Started process 107 to run task
[2025-04-14T20:14:25.710+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ihg_hotels_dag', 'load_to_snowflake', 'manual__2025-04-14T20:13:32.219908+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/hotel_scrape_dag.py', '--cfg-path', '/tmp/tmpdnwmc0o4']
[2025-04-14T20:14:25.711+0000] {standard_task_runner.py:105} INFO - Job 252: Subtask load_to_snowflake
[2025-04-14T20:14:25.726+0000] {task_command.py:467} INFO - Running <TaskInstance: ihg_hotels_dag.load_to_snowflake manual__2025-04-14T20:13:32.219908+00:00 [running]> on host 3bdf0eb8e71b
[2025-04-14T20:14:25.752+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ihg_hotels_dag' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T20:13:32.219908+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-14T20:13:32.219908+00:00'
[2025-04-14T20:14:25.753+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-14T20:14:25.757+0000] {hotel_scrape_dag.py:518} INFO - Connecting to Snowflake...
[2025-04-14T20:14:25.758+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-14T20:14:25.758+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-14T20:14:25.758+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-14T20:14:27.297+0000] {hotel_scrape_dag.py:537} INFO - Creating stage and table in Snowflake...
[2025-04-14T20:14:27.807+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-14T20:14:28.322+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-14T20:14:28.323+0000] {hotel_scrape_dag.py:563} INFO - Copying data from S3 to Snowflake table...
[2025-04-14T20:14:30.324+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-14T20:14:30.586+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-04-14T20:14:30.589+0000] {hotel_scrape_dag.py:574} INFO - Data loaded into Snowflake table: hotels (220 rows)
[2025-04-14T20:14:30.589+0000] {connection.py:789} INFO - closed
[2025-04-14T20:14:30.679+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-04-14T20:14:30.935+0000] {python.py:240} INFO - Done. Returned value was: 220
[2025-04-14T20:14:30.961+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-14T20:14:30.962+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ihg_hotels_dag, task_id=load_to_snowflake, run_id=manual__2025-04-14T20:13:32.219908+00:00, execution_date=20250414T201332, start_date=20250414T201425, end_date=20250414T201430
[2025-04-14T20:14:30.980+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-14T20:14:30.989+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T20:14:30.990+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
